---
- name: Check if prism central vm exists
  delegate_to: 127.0.0.1
  nutanix.ncp.ntnx_vms_info:
    nutanix_host: "10.38.26.37"
    nutanix_username: admin
    nutanix_password: "nx2Tech407!"
    validate_certs: false
    filter:
      vm_name: "{{ item.name }}"
    kind: vm
  register: nutanix_pc_vm_check
  ignore_errors: true
  loop: "{{ nutanix_pc_deploy_vm_list }}"

- name: Debug nutanix_pc_vm_check
  ansible.builtin.debug:
    msg: "{{ nutanix_pc_vm_check }}"
  when: nutanix_debug

- name: Too many VMs found
  ansible.builtin.fail:
    msg: "Too many VM name matches found for '{{ item.item.name }}'. Investigate cluster and retry playbook."
  loop: "{{ nutanix_pc_vm_check.results }}"
  loop_control:
    label: "{{ item.item }}"
  when:
    - item.response.metadata.length > 1

- name: Set nutanix_pc_vm_exists
  ansible.builtin.set_fact:
    nutanix_pc_vm_exists: true
  loop: "{{ nutanix_pc_vm_check.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.response.metadata.length == 1

- name: Debug nutanix_pc_vm_exists
  ansible.builtin.debug:
    msg: "{{ nutanix_pc_vm_exists | default(false) }}"
  when: nutanix_debug

- name: Get Prism Element registration state
  ansible.builtin.uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/PrismGateway/services/rest/v1/multicluster/cluster_external_state"
    method: GET
    validate_certs: "{{ validate_certs }}"
    headers:
      Authorization: "{{ nutanix_api_auth }}"
    status_code: 200
  register: nutanix_pc_register_current_state
  no_log: true

- name: Debug nutanix_pc_register_current_state.json
  ansible.builtin.debug:
    var: nutanix_pc_register_current_state.json
  when: nutanix_debug

- name: Set nutanix_pc_already_registered
  ansible.builtin.set_fact:
    nutanix_pc_already_registered: true
  when: nutanix_pc_register_current_state.json | length != 0

- name: Debug nutanix_pc_already_registered
  ansible.builtin.debug:
    var: nutanix_pc_already_registered
  when: nutanix_debug
