---
- name: Variable 'nutanix_pc_deploy_container_name' not defined
  ansible.builtin.fail:
    msg: "the variable 'nutanix_pc_deploy_container_name' is not defined."
  when:
    - nutanix_pc_deploy_container_name is not defined

- name: Variable 'nutanix_pc_deploy_subnet_name' not defined
  ansible.builtin.fail:
    msg: "the variable 'nutanix_pc_deploy_subnet_name' is not defined."
  when:
    - nutanix_pc_deploy_subnet_name is not defined

- name: Variable 'nutanix_pc_deploy_network_address' not defined
  ansible.builtin.fail:
    msg: "the variable 'nutanix_pc_deploy_network_address' is not defined."
  when:
    - nutanix_pc_deploy_network_address is not defined

- name: Variable 'nutanix_pc_deploy_gateway' not defined
  ansible.builtin.fail:
    msg: "the variable 'nutanix_pc_deploy_gateway' is not defined."
  when:
    - nutanix_pc_deploy_gateway is not defined

# - name: Variable 'nutanix_pc_deploy_ip_address' not defined
#   ansible.builtin.fail:
#     msg: "the variable 'nutanix_pc_deploy_ip_address' is not defined."
#   when:
#     - nutanix_pc_deploy_ip_address is not defined

- name: Variable 'nutanix_pc_deploy_dns_list' not defined
  ansible.builtin.fail:
    msg: "the variable 'nutanix_pc_deploy_dns_list' is not defined."
  when:
    - nutanix_pc_deploy_dns_list is not defined
    - nutanix_pc_deploy_dns_list | length > 0

- name: Variable 'nutanix_pc_deploy_size' not defined
  ansible.builtin.fail:
    msg: "the variable 'nutanix_pc_deploy_size' is not defined."
  when:
    - nutanix_pc_deploy_size is not defined

- name: Variable 'nutanix_pc_deploy_size' incorrect value
  ansible.builtin.fail:
    msg: "the variable 'nutanix_pc_deploy_size' is not set to ['small', 'large', 'xlarge']."
  when:
    - nutanix_pc_deploy_size not in ['small', 'large', 'xlarge']
