---
- name: Debug deployment HTTP POST body
  ansible.builtin.debug:
    msg: "{{ lookup('template', 'pc-deploy-rest-post-body.yml.j2') | from_yaml | to_nice_json }}"
  when: role_nutanix_pe_deploy_pc_debug

- name: Deploying Prism Central to Cluster
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/prism_central"
    method: POST
    validate_certs: "{{ role_nutanix_pe_deploy_pc_host_validate_certs }}"
    body_format: json
    body: "{{ lookup('template', 'pc-deploy-rest-post-body.yml.j2') | from_yaml | to_json }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 202
    return_content: true
  register: role_nutanix_pe_deploy_pc_task
  ignore_errors: false

- name: Wait for Prism Central deploy task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_pe_deploy_pc_host }}"
    role_nutanix_prism_monitor_task_host_username: "{{ role_nutanix_pe_deploy_pc_host_username }}"
    role_nutanix_prism_monitor_task_host_password: "{{ role_nutanix_pe_deploy_pc_host_password }}"
    role_nutanix_prism_monitor_task_host_port: "{{ role_nutanix_pe_deploy_pc_host_port }}"
    role_nutanix_prism_monitor_task_host_validate_certs: "{{ role_nutanix_pe_deploy_pc_host_validate_certs }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_pe_deploy_pc_debug }}"
    role_nutanix_prism_monitor_task_uuid: "{{ role_nutanix_pe_deploy_pc_task.json.task_uuid }}"
    role_nutanix_prism_monitor_task_retries: "{{ role_nutanix_pe_deploy_pc_retries }}"
    role_nutanix_prism_monitor_task_retry_delay: "{{ role_nutanix_pe_deploy_pc_delay }}"

- name: Set nutanix_pc_deploy_task
  ansible.builtin.set_fact:
    role_nutanix_pe_deploy_pc_task_result: "{{ role_nutanix_prism_monitor_task_result }}"

- name: Generate basic authorization string
  set_fact:
    role_nutanix_pe_deploy_pc_auth_string: "{{ role_nutanix_pe_deploy_pc_default_username }}:{{ role_nutanix_pe_deploy_pc_default_password }}"
  no_log: true

- name: Generate authorization header
  ansible.builtin.set_fact:
    role_nutanix_pe_deploy_pc_auth_string_b64: "Basic {{ role_nutanix_pe_deploy_pc_auth_string | b64encode(encoding='ascii') }}"
  no_log: true
  when: role_nutanix_pe_deploy_pc_auth_string is defined

- name: Unset basic authorization string
  ansible.builtin.set_fact:
    role_nutanix_pe_deploy_pc_auth_string: ""
  no_log: true
  when: role_nutanix_pe_deploy_pc_auth_string is defined

- name: Wait for Prism Central API to become available
  ansible.builtin.uri:
    url:
      "https://{{ role_nutanix_pe_deploy_pc_vip | default(role_nutanix_pe_deploy_pc_vm_list[0].ip_address) }}:{{ role_nutanix_pe_deploy_pc_host_port }}\
      /api/nutanix/v3/users/me"
    method: GET
    validate_certs: "{{ role_nutanix_pe_deploy_pc_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_pe_deploy_pc_auth_string_b64 }}"
  ignore_errors: true
  register: role_nutanix_pe_deploy_pc_api_test
  until: "role_nutanix_pe_deploy_pc_api_test.status == 200"
  retries: 30
  delay: 10
