---
- name: grdavies.role_nutanix_prism_api
  src: https://github.com/grdavies-ansible/role_nutanix_prism_api
  version: "1.2.2"
- name: grdavies.role_nutanix_prism_monitor_task
  src: https://github.com/grdavies-ansible/role_nutanix_prism_monitor_task
  version: "1.1.10"
- name: grdavies.role_nutanix_prism_initial_password
  src: https://github.com/grdavies-ansible/role_nutanix_prism_initial_password
  version: "1.1.4"
- name: grdavies.role_nutanix_prism_eula
  src: https://github.com/grdavies-ansible/role_nutanix_prism_eula
  version: "1.1.3"
- name: grdavies.role_nutanix_prism_pulse
  src: https://github.com/grdavies-ansible/role_nutanix_prism_pulse
  version: "1.1.3"
- name: grdavies.role_nutanix_pe_container_search
  src: https://github.com/grdavies-ansible/role_nutanix_pe_container_search
  version: "1.1.6"
