---
- name: grdavies.role_nutanix_prism_api
  version: "1.2.1"
- name: grdavies.role_nutanix_prism_monitor_task
  version: "1.1.4"
- name: grdavies.role_nutanix_prism_initial_password
  version: "1.1.3"
- name: grdavies.role_nutanix_prism_eula
  version: "1.1.2"
- name: grdavies.role_nutanix_prism_pulse
  version: "1.1.2"
- name: grdavies.role_nutanix_pe_container_search
  version: "1.1.5"
